kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  IndexedJob: true
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
      endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    image: kindest/node:v1.22.1
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP
