apiVersion: skaffold/v2beta19
kind: Config
metadata:
  name: rft
build:
  local:
    useBuildkit: true
    push: true
  artifacts:
    - image: localhost:5000/rft-controller
      context: .
      docker:
        dockerfile: ./rft-controller/Dockerfile
        cacheFrom:
          - "rust:latest"
          - "debian:buster-slim"
    - image: localhost:5000/rft-gateway
      context: .
      docker:
        dockerfile: ./rft-controller/Dockerfile
        cacheFrom:
          - "rust:latest"
          - "debian:buster-slim"

deploy:
  helm:
    releases:
      - name: rft
        chartPath: ./rft-chart
        setValueTemplates:
          redis:
            auth:
              password: "{{.REDIS_PASSWORD}}"
        artifactOverrides:
          controller:
            image: localhost:5000/rft-controller
          gateway:
            image: localhost:5000/rft-gateway

portForward:
  - resourceType: service
    resourceName: rft-gateway-svc
    namespace: default
    port: 8000
    localPort: 8000
