[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "rft_worker_sdk"
author = "Matthew Conway"
home-page = "https://github.com/retwolf"
classifiers = ["License :: OSI Approved :: MIT License"]
