apiVersion: v2
name: r5t-chart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: redis
  version: ">= 10.9.0"
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled